trigger:
- none
parameters:
- name: location
  displayName: "Azure region"
  type: string
  default: 'eastus'

- name: customer_client_id
  displayName: "Customer Client ID"
  type: string
  default: "ad019710-d8a6-46ad-add7-c05a9e9da443"

- name: customer_client_secret
  displayName: "Customer Client Secret"
  type: string
  default: "viG8Q~afrRrjdtZOEaQzTnEFLw1ThJqMkSPendfj"
  
  
- name: customer_tenant_id
  displayName: "Customer Tenant ID"
  type: string
  default: "e22861cb-ba60-48a7-8d82-fa8e4267a5bd"

- name: customer_subscription_id
  displayName: "Customer Subscription ID"
  type: string
  default: "f5980816-b478-413b-ae0b-5fb6d820a88f"
  
- name:  default_domain_name
  displayName: "Default Domain Name"
  type: string
  default: "mohamedomar18live"

- name: customer_subscription_owner_first_name
  displayName: "Subscription Owner First Name"
  type: string
  default: "devops"

- name: customer_subscription_owner_last_name 
  displayName: "Subscription Owner Last Name"
  type: string
  default: "1"




stages:
- stage: 'Terraform_Apply'
  displayName: 'Terraform Apply'
  jobs:
  - deployment: 'Terraform_Apply'
    pool: default
    environment: 'testenv'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - script: |
              echo "Location: ${{ parameters.location }}"
              echo  ${BUILD_ID}
            displayName: 'Print Parameter Values'
          - script: |
              terraform workspace new my_workspace_${BUILD_ID}
            displayName: 'Create new Terraform workspace' 
          - script: |
              terraform workspace select my_workspace_${BUILD_ID}
            displayName: 'Select the new Terraform workspace'
          - script: |
              terraform init
            displayName: 'Terraform Init'
          - script: |
              terraform plan -var customer_subscription_id=${{ parameters.customer_subscription_id }} -var customer_client_id=${{ parameters.customer_client_id}} -var customer_tenant_id=${{ parameters.customer_tenant_id }} -var customer_client_secret=${{ parameters.customer_client_secret }} -var location=${{ parameters.location }} -var domain_name=${{parameters.default_domain_name}} -var customer_subscription_owner_first_name=${{parameters.customer_subscription_owner_first_name}} -var customer_subscription_owner_last_name=${{parameters.customer_subscription_owner_last_name}}  -out=tfplan
              
            displayName: 'Terraform Plan'
          - script: |
              terraform apply --auto-approve -var customer_subscription_id=${{ parameters.customer_subscription_id }} -var customer_client_id=${{ parameters.customer_client_id}} -var customer_tenant_id=${{ parameters.customer_tenant_id }} -var customer_client_secret=${{ parameters.customer_client_secret }} -var location=${{ parameters.location }} -var domain_name=${{parameters.default_domain_name}} -var customer_subscription_owner_first_name=${{parameters.customer_subscription_owner_first_name}} -var customer_subscription_owner_last_name=${{parameters.customer_subscription_owner_last_name}}  
            displayName: 'Terraform Apply'
          - script: |
             terraform output "customer_subscription_owner_password"
            displayName: 'Output Password'