trigger:
- none

pool: default

steps:
  # Checkout the repository
  - checkout: self
    fetchDepth: 0
  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'SonarQube-MSabeq'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'Solution_Hub_Solution_Hub_AZOTL4tL1j29lUBeEaYW'
      cliSources: '.'
  - task: SonarQubeAnalyze@7
  - task: SonarQubePublish@7
    inputs:
      pollingTimeoutSec: '300'